---
abstract: "Clone of PHP's date and time functions."
author:
  - 'Aran Clary Deltac <bluefeet@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.62
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PHP-DateTime
no_index:
  directory:
    - inc
    - t
recommends:
  Test::Pod: 1.22
requires:
  Time::DaysInMonth: 0
  Time::HiRes: 0
  Time::Local: 0
  Time::Timezone: 0
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
